[package]
edition = "2021"
name = "devshare-native"
version = "0.1.0"
description = "Native Rust addon for DevShare cryptography and compression"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
# NAPI-RS for Node.js bindings
napi = { version = "2.16", default-features = false, features = ["napi4"] }
napi-derive = "2.16"

# Cryptography
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
aes-gcm = "0.10"
sha2 = "0.10"
rand = "0.8"

# Compression
zstd = "0.13"

# Utilities
hex = "0.4"
thiserror = "1.0"

[build-dependencies]
napi-build = "2.1"
