/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sha256(data: Buffer): Buffer
export declare function zstdCompress(data: Buffer): Buffer
export declare function zstdDecompress(data: Buffer): Buffer
export declare function generateKeypair(): KeyPair
export declare function signData(privateKey: string, data: Buffer): string
export declare function verifySignature(publicKey: string, signature: string, data: Buffer): boolean
export declare function encryptAesGcm(key: Buffer, nonce: Buffer, data: Buffer): Buffer
export declare function decryptAesGcm(key: Buffer, nonce: Buffer, encryptedData: Buffer): Buffer
export declare function generateRandomBytes(length: number): Buffer
export interface KeyPair {
  publicKey: string
  privateKey: string
}
